server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      force: true
    context-path: /

spring:
  # 数据源配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bookmana?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: 'root'
    # 数据库初始化
    sql:
      init:
        mode: always
        schema-locations: classpath:schema.sql
    # 连接池配置
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      idle-timeout: 300000
      connection-timeout: 20000
  
  # Redis配置
  redis:
    host: localhost
    port: 6379
    database: 0
    timeout: 10000
    lettuce:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
  
  # 缓存配置
  cache:
    type: redis
    redis:
      time-to-live: 3600000  # 缓存过期时间1小时
      cache-null-values: true # 是否缓存空值
      use-key-prefix: true   # 是否使用前缀
      key-prefix: "book:"    # 缓存key的前缀
  
  # JSON配置
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: NON_NULL
  
  # MVC配置
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true
  main:
    allow-circular-references: true

# MyBatis-Plus配置
mybatis-plus:
  configuration:
    # 开发环境打印SQL
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # 关闭缓存
    cache-enabled: false
    local-cache-scope: statement
    # 下划线转驼峰
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      # 主键策略
      id-type: auto
    banner: false
  # XML文件位置
  mapper-locations: classpath:mapper/*.xml
  # 实体类包路径
  type-aliases-package: com.example.book_management.entity

# 日志配置
logging:
  level:
    root: INFO
    com.example.book_management: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
